# Generated by Django 3.2.13 on 2022-06-17 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル[必須]')),
                ('publish', models.DateField(blank=True, null=True, verbose_name='公開日[必須]')),
                ('validthrough', models.DateField(blank=True, null=True, verbose_name='公開終了日[必須]')),
                ('company', models.CharField(blank=True, default='合同会社マーリー', max_length=100, null=True, verbose_name='会社名[必須]')),
                ('country', models.CharField(blank=True, default='JP', max_length=10, null=True, verbose_name='国名[必須]')),
                ('memo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
