# Generated by Django 3.2.13 on 2022-06-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='memo2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
